### ISSUE TITLE
Add notes and icons to map

### ISSUE THREAD

**Issue by simonolle** [syradar/yxans-klagan#123]
skulle vilja se att man kunde spara lätt information på kartan, 
man vill ju ha så pass mycket text att man kan så man kan spara ett namn på platsen, vad det är för plats och även så man kan länka till egen informations källa, tex onenote, Evernote, Notion, NoteLedge.

för att slippa hålla server och dylikt så spara bara på i läsaren, 
en spara knapp så man kan spara informationen till datorn ifall man behöver byta läsare eller ominstallera om datorn.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by syradar** [comment]
Information from #114 moved here to keep it all in one place.

**Is your feature request related to a problem? Please describe.**
> I'm loving this tool more and more! One thing I'd like to ask you is to have more maneuverability with the map section. Like the ability to add notes/icons to the map so that I can keep track of which adventure sites are where 

**Describe the solution you'd like**
1. Click on a map tile
2. Be able to choose an icon in the popup
3. Be able to write a small note

**Describe alternatives you've considered**
Keeping notes on each tile in a separate document

**Additional context**
Concerns: Input validation, Persistence

**Comment by syradar** [comment]
No time
