### ISSUE TITLE
[Bug] There are no scenarios; must have at least one.

### ISSUE THREAD

**Issue by GAZ082** [syradar/yxans-klagan#241]
Im trying to run it and after executing yarn I get the error of the subject.

What am I doing wrong/missing?

Thanks.

**Comment by syradar** [comment]
I have been doing a bad job maintaining this so the dependencies are out of date.
But you should be able to install them by running `yarn` or `npm install` and then either `yarn start` or `npm run start`.
When do the error appear? Can you post a screenshot or log of the error?

**Comment by GAZ082** [comment]
Hi David,

No issues. Looks like in Debian installing the yarn package does not cut it. Properly intalled it and managed to run it only to have another bug that ill put in another thread.

Thanks!
