### ISSUE TITLE
[Bug] click on Map Hex is not triggered correctly

### ISSUE THREAD

**Issue by Gustafssonz** [syradar/yxans-klagan#268]
**Describe the bug**
When clicking on the Hexes, the parchment is null and therefore not triggering the 'handleHexClick' correctly.

**To Reproduce**
1. Go to Map
2. Click on any hex

**Expected behavior**
Not sure what is suppose to happen.  This I guess:
setMapPopover({
        hex,
        x: rect.left,
        y: rect.top,
        mapMinX: parchmentRect.x,
        mapMaxX: parchmentRect.width,
        mapMinY: parchmentRect.y,
        mapMaxY: parchmentRect.height,
      })

**Screenshots**
![image](https://user-images.githubusercontent.com/22516790/211920219-390e6dd5-8351-47f4-8b2d-1e56007b2784.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: Firefox    and Edge Version
 : Firefox  108.0.2 (64-bit) 
 Edge Version 108.0.1462.76

**Smartphone (please complete the following information):**

**Additional context**
I try to solve it myself but I was to lazy and haven't been working with much SVG. Riktigt jävla bra sida annars!

**Comment by syradar** [comment]
I will try to take a look at the bug this weekend. Thank you for the detailed bug report! <3

**Comment by syradar** [comment]
I got excited and decided to fix it right away :)
Kul att du gillar sidan :)
