### ISSUE TITLE
Alternative Map support (Bitter Reach)

### ISSUE THREAD

**Issue by Vandenberg** [syradar/yxans-klagan#277]
I am a player in a Bitter Reach campaign and my GM would like to use the Map feature to track our progress. Could you make it possible to use the map from Bitter Reach instead of the Ravenland?

For example, the user could upload a map of their own to use instead. Or there could be additional pages with different maps. 

I would really love it if this feature became implemented, and I am sure so would others.

**Comment by syradar** [comment]
- [ ] Test
