### ISSUE TITLE
[Bug] Bottom part of gear table does not translate to English from Swedish

### ISSUE THREAD

**Issue by Helmaer** [syradar/yxans-klagan#339]
**Describe the bug**
When I tab into the Gear Tables with the language set to English, the bottom table list (labelled Vanliga tjänster) [that I think is the list of workers available] remains in Swedish. I cannot make this change into English.  

**To Reproduce**
1. Go to '...' [Gear Tables](https://yxans-klagan.vercel.app/gear/tables?fbclid=IwAR3fvPV6qzMSNXpaChpC1AeTEDLX5C9Ofq7IfjiawnHY1J0ZY7ISKdS0HQk)
2. Click on '....' Gears Table -> English
3. Scroll down to '....' Vanliga tjänster
4. See error: Remains in Swedish

**Expected behavior**
I would hope the bottom table would translate into English.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Intel Core i5 with Windows Home 10
 - Browser: Chrome

**Additional context**

**Comment by syradar** [comment]
@Helmaer Thank you, the plan is to add the rest of the gear to the page and provide ways to filter them. Also being able to add stuff to a shopping cart and more. Tracked by #340
