### ISSUE TITLE
[Feature Request]: Map with fog of war

### ISSUE THREAD

**Issue by Jagullov** [syradar/yxans-klagan#54]
I like the feeling of exploration, and my group of players are playing FL with no knowledge of Ravenland map.

For this reason, I hide all the map and they can only see the explored hexes, like the fog of war. So, if is it possible to add an option in the Map section that can hide (blackout) all the map hexes, and only shows the explored hexes.

One example of this is the Foundry VTT map and how it work the illumination.

Thanks in advance!

**Comment by syradar** [comment]
Would something like this be good? 
![image](https://user-images.githubusercontent.com/10453338/137408171-3fbdcdac-f190-41f3-8bc6-92ba83b28c05.png)
